### ISSUE TITLE
Patches for USB and Ethernet are not included in the SRC_URI variables

### ISSUE THREAD

**Issue by darko31** [Seeed-Studio/meta-st-odyssey#2]
Hello, it seems that patches from this commit 

https://github.com/Seeed-Studio/meta-st-odyssey/commit/0b93e8b7688125f3ac96103001721c5bdcf98e79

are not applied. They aren't included in the SRC_URI variables for ATF, U-boot and kernel recipes.
They do work as expected after adding them to SRC_URI manually.

**Comment by leadercxn** [comment]
![image](https://user-images.githubusercontent.com/43691182/141288409-c88b468c-7c0a-4d20-921b-556aeea0cdb6.png)

**Comment by leadercxn** [comment]
Hi @darko31,

**Comment by leadercxn** [comment]
@darko31

**Comment by leadercxn** [comment]
Hi @darko31

Do you mean that you can't do fetch ATF, U-boot and kernel recipes automatically?
Here is my operation log:
![image](https://user-images.githubusercontent.com/43691182/141289445-1e2beeca-2007-416e-8095-80cdf844f8ae.png)

Thanks~
JackyChen.

**Comment by leadercxn** [comment]
@darko31 
Oh yep, I forget that add the patch to the *.bbappend files .
Now I have modified them.

Thanks~
JackyChen
